// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'expenses/expense_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8694174257024859892),
    name: 'Expense',
    lastPropertyId: const obx_int.IdUid(11, 3949942212076874165),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6828260155093473401),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3725361405003131430),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7530753519007405932),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2709924213008104471),
        name: 'schemaVersion',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3949942212076874165),
        name: 'money',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 8694174257024859892),
    lastIndexId: const obx_int.IdUid(1, 4797485126035178209),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      8526317472726263789,
      8293366740837241128,
      4038058507507609255,
    ],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      4776833521126459171,
      3948883220458621421,
      5714188052595103927,
      1010344018086141909,
      1327634009688833588,
      3414006024218173339,
      7523321317004397021,
      687115844222007862,
      9178105703090153528,
      5217994620048866311,
      892546092346003791,
      4715777236749734410,
      5469530778652803120,
      7365158824009652158,
      4384838249052737865,
      7198587605743826052,
      5998621694080196278,
      3513537160816694553,
      1030027131171780880,
      3985531746700708375,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Expense: obx_int.EntityDefinition<Expense>(
      model: _entities[0],
      toOneRelations: (Expense object) => [],
      toManyRelations: (Expense object) => {},
      getId: (Expense object) => object.id,
      setId: (Expense object, int id) {
        object.id = id;
      },
      objectToFB: (Expense object, fb.Builder fbb) {
        final noteOffset = fbb.writeString(object.note);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(2, noteOffset);
        fbb.addInt64(3, object.date.millisecondsSinceEpoch);
        fbb.addInt64(9, object.schemaVersion);
        fbb.addInt64(10, object.money);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Expense()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..note = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..date = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
          )
          ..schemaVersion = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            22,
            0,
          )
          ..money = const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Expense] entity fields to define ObjectBox queries.
class Expense_ {
  /// See [Expense.id].
  static final id = obx.QueryIntegerProperty<Expense>(
    _entities[0].properties[0],
  );

  /// See [Expense.note].
  static final note = obx.QueryStringProperty<Expense>(
    _entities[0].properties[1],
  );

  /// See [Expense.date].
  static final date = obx.QueryDateProperty<Expense>(
    _entities[0].properties[2],
  );

  /// See [Expense.schemaVersion].
  static final schemaVersion = obx.QueryIntegerProperty<Expense>(
    _entities[0].properties[3],
  );

  /// See [Expense.money].
  static final money = obx.QueryIntegerProperty<Expense>(
    _entities[0].properties[4],
  );
}
